config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

  resources :puzzles, only: [:index, :show, :create, :update, :destroy] do
    member do
      post :reset
    end
  end

  resource :settings, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/number.rb
class Number < ApplicationRecord
  BLANK_SYMBOL = '_'.freeze
  belongs_to :puzzle

  before_save :setup_numbers, :if => :new_record?

  def correct_answer_array
    correct_answer.chars.map { |n| n.to_i }
  end

  def question_array
    question.chars.map { |n| n == BLANK_SYMBOL ? nil : n.to_i }
  end

  def thinking_answer_array
    thinking_answer.chars.map { |n| n == BLANK_SYMBOL ? nil : n.to_i }
  end

  private

  def setup_numbers
    logger.info "********** start setup_numbers **********"
    logger.info "creating correct_answer"
    correct_answer_array = generate_correct_answer_array
    self.correct_answer = correct_answer_array.join

    logger.info "creating question and thinking_answer"
    self.question = generate_question(correct_answer_array)
    self.thinking_answer = self.question
    logger.info "********** finish setup_numbers **********"
  end

  def generate_correct_answer_array
    tmp_table = 81.times.map { |i| nil }
    table = []
    try_limit = 100 # 試行回数の上限

    group_indexes = [0, 3, 6, 27, 30, 33, 54, 57, 60].map do |i|
      (i..(i + 2)).to_a + (i + 9..(i + 11)).to_a + (i + 18..(i + 20)).to_a
    end
    # group_indexes
    # ---------------------------------------
    # | group_indexes[0] |  group_indexes[1] |  group_indexes[2] |
    # | group_indexes[3] |  group_indexes[4] |  group_indexes[5] |
    # | group_indexes[6] |  group_indexes[7] |  group_indexes[8] |
    # ---------------------------------------

    tmp_table.each_slice(9).with_index do |row, row_index|
      if row_index.zero?
        table += (1..9).to_a.shuffle
        next
      end

      try_limit.times do
        new_row = []
        row.each_with_index do |column, column_index|
          table_index = 9 * row_index + column_index

          # 縦の数
          select_indexes = []
          i = table_index
          while i >= 9 do
            i -=9
            select_indexes << i
          end
          column_numbers = select_indexes.map { |i| table[i] }

          # 横の数
          row_numbers = new_row

          # ブロックの数
          group_index = group_indexes.find_index { |index| index.include?(table_index) }
          group_numbers = group_indexes[group_index].map {|i| table[i] }

          # 値の選択
          reject_numbers = (column_numbers + row_numbers + group_numbers).compact.uniq
          enable_numbers = (1..9).to_a - reject_numbers
          new_row << enable_numbers.sample
        end

        unless new_row.include?(nil)
          table += new_row
          break
        end
      end
    end

    if table.include?(nil)
      logger.info "can't find numners! recreating a question"
      generate_correct_answer_array
    elsif table.size != 81
      logger.info "table size is not 81! recreating a question"
      generate_correct_answer_array
    else
      table
    end
  end

  def generate_question(question_array)
    hidden_cell_size = case puzzle.challenge_level
                         when 'easy'
                            2
                         when 'normal'
                            5
                         when 'hard'
                            6
                         end

    question_array.each_slice(9).map do |row|
      hidden_cells = (1..9).to_a.sample(hidden_cell_size)
      row.map do |cell|
        hidden_cells.include?(cell) ? BLANK_SYMBOL : cell
      end
    end.flatten.join
  end
end

app/models/puzzle.rb
class Puzzle < ApplicationRecord
  has_one :number, dependent: :destroy

  enum :status, %i(draft submitted completed)
  enum :challenge_level, %i(easy normal hard)
end

app/models/setting.rb
class Setting < ApplicationRecord
  enum :challenge_level, %i(easy normal hard)
  enum :theme, %i(default dark)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :production?
  before_action :set_theme

  private

  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |name, password|
      name == ENV["BASIC_AUTH_NAME"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def set_theme
    @theme = Setting.first.theme
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
  before_action :set_puzzle, only: [:show, :update, :reset, :destroy]
  before_action :set_setting, only: [:create]

  def index
    flash[:notice] = 'やっぼー'
    @puzzles = Puzzle.order(updated_at: :desc)
  end

  def create
    puzzle = Puzzle.new(status: :draft, challenge_level: @setting.challenge_level)
    puzzle.build_number
    puzzle.save!

    redirect_to puzzle_path(puzzle)
  end

  def show
    flash[:notice] = 'がんばろー'
  end

  def update
    new_answer_array = @puzzle.number.thinking_answer_array

    answer_params.each do |k, v|
      index = k.split('_').last.to_i
      new_answer_array[index] = v.blank? ? Number::BLANK_SYMBOL : v.to_i
    end

    status = (new_answer_array == @puzzle.number.correct_answer_array) ? :completed : status_param

    @puzzle.update!(status: status)
    @puzzle.number.update!(thinking_answer: new_answer_array.join)

    if @puzzle.draft?
      redirect_to puzzles_path
    elsif @puzzle.completed?
      flash[:success] = "completed"
      redirect_to puzzles_path
    else
      redirect_to puzzle_path(@puzzle)
    end
  end

  def reset
    @puzzle.update!(status: :draft)
    @puzzle.number.update!(thinking_answer: @puzzle.number.question)

    redirect_to puzzle_path(@puzzle)
  end

  def destroy
    @puzzle.destroy!

    redirect_to puzzles_path
  end

  private

  def set_puzzle
    @puzzle = Puzzle.find(params[:id])
  end

  def set_setting
    @setting = Setting.first # TODO: User ができたら current_user.setting にしたい
  end

  def answer_params
    permit_indexes = (0..80).to_a.map { |n| "index_#{n}".to_sym }
    params.require(:answer).permit(permit_indexes)
  end

  def status_param
    params.require(:status)
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:edit, :update]

  def edit; end

  def update
    @setting.update!(setting_params)

    flash[:notice] = "更新したよ！"
    redirect_to root_path
  end

  private

  def set_setting
    @setting = Setting.first # TODO: User ができたら current_user.setting にしたい
  end

  def setting_params
    params.require(:setting).permit(:challenge_level, :theme)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/puzzle_helper.rb
module PuzzleHelper
  def wrong_answer?(index, column)
    return false unless @puzzle.status == 'submitted'

    @puzzle.number.correct_answer_array[index] != column
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>なんぷれ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cherry+Bomb+One&family=M+PLUS+1:wght@200&family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="<%= @theme %>">
    <header>
      <h1 class="app_title"><%= link_to 'なんぷれ', root_url %></h1>
      <%= link_to '設定', edit_settings_url, class: 'no-print' %>
    </header>
    <div class="body">
      <%= yield %>
    </div>
    <footer>
      &copy; 2023 ckanayama
    </footer>
    <%- if flash[:notice] %>
      <div id="comment" class="no-print"><%= flash[:notice] %></div>
    <%- end %>
    <canvas id="maru" class="no-print"></canvas>
  </body>
</html>

app/views/pages/home.slim
.home
  = button_to 'あたらしい問題に挑戦する', puzzles_path, class: 'home_links_new'
  = link_to '履歴をみる', puzzles_path, class: 'home_links_index'

app/views/puzzles/index.slim
.history
  - if flash[:success]
    .history_overlay
    - animal = ['usa', 'piyo', 'kuma'].sample
    = image_tag "history/omede#{animal}.png", class: 'history_success'

  table.history_table
    tbody
      - @puzzles.each do |puzzle|
        tr
          td = "No.#{puzzle.id}"
          td = (I18n.l puzzle.updated_at, format: :long)
          td = Puzzle.human_attribute_name("challenge_level.#{puzzle.challenge_level}")
          td
            - if puzzle.status != 'completed'
              = link_to '再開する', puzzle_path(puzzle), class: 'history_restart'
          td = button_to 'x', puzzle_path(puzzle), method: :delete, class: 'history_delete'

app/views/puzzles/show.slim
.puzzle
  = "No. #{@puzzle.id}"
  = form_with scope: :answer, url: puzzle_path(@puzzle), method: :patch do |form|
    - @puzzle.number.thinking_answer_array.each_slice(9).with_index do |row, row_index|
      .puzzle_row
        - row.each_with_index do |number, column_index|
          - index = row_index * 9 + column_index
          - if @puzzle.number.question_array[index].present?
            div.puzzle_column id=" index_#{index}"
              = number
          - else
            div class="puzzle_column #{'wrong' if wrong_answer?(index, number)}" id="index_#{index}"
              = form.number_field "index_#{index}", in: 1..9, class: 'puzzle_column_input', value: number
    .puzzle_main_action
      = form.button type: 'submit', name: 'status', value: 'draft', class: 'btn puzzle_draft no-print' do
        | 中断する
      = form.button type: 'submit', name: 'status', value: 'submitted', class: 'btn puzzle_submit no-print' do
        = Puzzle.human_attribute_name('status.submitted')
        | する
  = button_to 'リセットする', reset_puzzle_path(@puzzle), method: :post, class: 'btn puzzle_reset no-print'

app/views/settings/edit.slim
.setting
  = form_with model: @setting, url: settings_path, method: :patch do |f|
    .setting_form_inner
      div = f.label Setting.human_attribute_name("challenge_level")
      div = f.select :challenge_level, Setting.challenge_levels.keys.map { |key| [Setting.human_attribute_name("challenge_level.#{key}"), key] }
      div = f.label Setting.human_attribute_name("theme")
      div = f.select :theme, Setting.themes.keys.map { |key| [Setting.human_attribute_name("theme.#{key}"), key] }
    div = f.submit '更新する', class: 'setting_submit'